[tool.poetry]
name = "a"
version = "0.1.0"
description = ""
authors = ["Huon Wilson <huon@exoflare.io>"]

[tool.poetry.dependencies]
python = "^3.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
